#!/bin/bash
tolower() {
  tr '[:upper:]' '[:lower:]'
}

dir="`dirname "$0"`"
arch="`uname -m | tolower`"
os="`uname | tolower`"
bindir="${dir}/bin/${os}/${arch}/"
exe="$bindir/inexor"

export LD_LIBRARY_PATH="$bindir:$LD_LIBRARY_PATH"
echo >&2 "CALLING: ${exe}"
find "$dir"/data/ -maxdepth 1 -print0                      \
  | sed 's/^/-k/' -z                                       \
  | xargs --null "${exe}" -q"~/.inexor"
