#!/bin/bash
tolower() {
  tr '[:upper:]' '[:lower:]'
}

dir="`dirname "$0"`"
arch="`uname -m | tolower`"
os="`uname | tolower`"
exe="${dir}/bin/${os}/${arch}/inexor"

export LD_LIBRARY_PATH="$OLIB:pref;bin_linux/"
echo >&2 "CALLING: ${exe}"
find "$dir"/data/ -maxdepth 1 -print0                      \
  | sed 's/^/-k/' -z                                       \
  | xargs --null "${exe}" -q"~/.inexor"
